.\" Manpage for SAFETy.
.\" Contact adasneves127@gmail.com to correct errors or typos.
.TH man 1 "12 March 2023" "1.1" "SAFETy man page"
.SH NAME
SAFETy -- A Simulator for the SAFETy Computer, Designed by Alex Dasneves
.SH SYNOPSIS
SAFETy [[-e] | <ROM File> <RAM File> <Header File>] [-d] [-m]
.SH DESCRIPTION
SAFETy is a turing complete computer, designed by Alex Dasneves, with the help of Lyra Brown, and Dr. Margaret Black, all affiliated with Bridgewater State University.
SAFETy is designed as an improvement on Dr. Margaret Black's RISCy Computer, which was designed as a RISC processor. Seeing the minor deficiencies with RISC, we designed SAFETy, which was
specifically designed to implement some creature comforts.
.SH OPTIONS
SAFETy [[-e] | <ROM File> <RAM File> <Header File>] [-d] [-m]
Options:
    -e      Initialize the Sim with empty memory (All 0x00)
    -d      Enable Debug Mode. Prints the system status after every instruction run.
    -m      Initialize the Sim, and enter the monitor.
    -r      Raw output mode (Print the direct hex values when writing to video memory).

.SH BUGS
No known bugs.
.SH AUTHOR
Alex Dasneves (adasneves@adasneves.info)

Lyra Brown (lbrown@lbrown.info)
