name: Feature Request
description: Request a new feature
title: "Feature Request: "
labels: ["Feature Request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this Feature Request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: Is this a Hardware or Software request?
      options:
        - Hardware
        - Software
    validations:
      required: true
  - type: textarea
    id: Describe_Request
    attributes:
      label: Description
      description: Also, do you have any design ideas or extra goals for this request?
      placeholder: Tell us about it!
      value: "Create an IDE"
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
